version: 2
enable-beta-ecosystems: true
updates:
  # Workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Workspace pubspec.yaml
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # Examples
  - package-ecosystem: "pub"
    directory: "/examples/explorer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/examples/service_manager_cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/examples/task_manager"
    schedule:
      interval: "weekly"

  # Packages
  - package-ecosystem: "pub"
    directory: "/packages/generator"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/win32"
    schedule:
      interval: "weekly"
